# Makefile

# em,ulator for local testing: https://cloud.google.com/functions/docs/emulator


install:
	sudo npm install -g @google-cloud/functions-emulator

incidents.json:
	curl https://status.cloud.google.com/incidents.json > incidents.json